GLOBAL_MAPPER_SCRIPT VERSION="1.00"

LAYER_LOOP_START FILENAME="obs_area"
    IF COMPARE_STR="'ENCLOSED AREA'<2000" COMPARE_NUM=YES
	EDIT_VECTOR \
	FILENAME="obs_area"\
	DELETE_FEATURES=YES
END_IF
LAYER_LOOP_END