GLOBAL_MAPPER_SCRIPT VERSION="1.00"

ADD_MEASURE_ATTRS \
	FILENAME="obs_area" \
	AREA_UNITS="SQUARE FEET" \
	MEASURE_UNIT_TYPE="BASE"    

EDIT_VECTOR \
	FILENAME="obs_area"\
	DELETE_FEATURES=YES \
	//AREA_UNITS="SQUARE FEET" \
	COMPARE_STR="ENCLOSED_AREA<20000" \
	COMPARE_NUM=YES
EDIT_VECTOR \
	FILENAME="obs_area"\
	DELETE_FEATURES=YES \
	AREA_UNITS="SQUARE FEET" \
	COMPARE_STR="ISLAND_AREA<20000" \
	COMPARE_NUM=YES

//LAYER_LOOP_END