GLOBAL_MAPPER_SCRIPT VERSION="1.00"

import FILENAME="C:\\Users\\AirWorksProcessing\\Documents\\Scripts\\2710.las"
LOG_MESSAGE %TIMESTAMP%: Step1 done

GENERATE_ELEV_GRID FILENAME="C:\\Users\\AirWorksProcessing\\Documents\\Scripts\\2710.las" LAYER_DESC="data_grid" GRID_TYPE=ELEVATION GRID_ALG=BIN_AVG ELEV_UNITS=FEET SPATIAL_RES_METERS=0.9 NO_DATA_DIST_MULT=0
LOG_MESSAGE %TIMESTAMP%: Step2 done