GLOBAL_MAPPER_SCRIPT
//for rasterization of .tif, .laz or .las files into a single .tif file

DEFINE_VAR\
  NAME="FILEORFOLDER"\
  PROMPT="Single file=YES, Many tiles in a folder=NO"

IF COMPARE_STR="%FILEORFOLDER%=YES"
  DEFINE_VAR\
    NAME="FILE"\
    PROMPT="SELECT A FILE"\
    FILE
  IMPORT FILENAME="%FILE%"
END_IF

ELSE COMPARE_STR="%FILEORFOLDER%=YES"
  DEFINE_VAR\
    NAME="FOLDER"
    PROMPT="SELECT A FOLDER CONTAINING DESIRED POINTCLOUDS"
    DIR
  DIR_LOOP_START DIRECTORY="%FOLDER%" FILENAME_MASKS= "*.tif" RECURSE_DIR=YES
    IMPORT FILENAME="%FNAME_W_DIR%"
  DIR_LOOP_END
END_IF

//Specify output name and location
DEFINE_VAR\
    NAME="OUTPUT"
    PROMPT="SELECT A FOLDER CONTAINING DESIRED POINTCLOUDS"
    DIR
//DEFINE_VAR\
    //NAME="NAME"
    //PROMPT="SELECT A FOLDER CONTAINING DESIRED POINTCLOUDS"
    //DIR

EXPORT_RASTER FILENAME "%OUTPUT%\aaa.tif" TYPE=GEOTIFF PALETTE=OPTIMIZED

UNLOAD_ALL